name: Lint

on: [push, pull_request]

jobs:

  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: sudo apt-get install -y libolm-dev python3-olm
    - name: Install dependencies (pip)
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install pylint
      run: python -m pip install pylint
    - name: pylint version
      run: pylint --version
    - name: Run pylint
      run: pylint $(git ls-files '*.py') --max-line-length=120 --exit-zero --disable=W1201,W1203
